name: Java CI with Maven

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8.0.452+9'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B install --file roman-number/pom.xml
      working-directory: progetto2mtss
    - name: Test with JaCoCo
      run: mvn test jacoco:report
      working-directory: progetto2mtss
